#########################
# Django 4 using pip
#   platform ssh 'python manage.py generate_fake_data' to seed data on prod
##########################
# Container configuration.

#   The name of this app. Must be unique within a project.
name: 'app'

#   The runtime the application uses.
type: 'python:3.9'

dependencies:
    python3:
        pipenv: '2022.9.4'

##########################
# Builds and variables

# runtime:
#     extensions:
#         - blackfire

# variables:
#     env:
#         BLACKFIRE_AGENT_SOCKET: "tcp://blackfire.platform.sh:8307"

hooks:
    build: |
        set -eu

        # Download the latest version of pip
        python -m pip install --upgrade pip

        # Install dependencies
        pipenv install --deploy
        # Collect static assets
        pipenv run python manage.py collectstatic
    deploy: pipenv run python manage.py migrate

##########################
# Web configuration

# The configuration of the application when it is exposed to the web.
web:
    upstream:
        socket_family: unix
    commands:
        # start: "blackfire-python gunicorn -w 4 -b unix:$SOCKET bigfoot_django.wsgi:application"
        start: "pipenv run blackfire-python python manage.py runserverß"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

##########################
# Services

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:postgresql"

##########################
# Data and mounts

# The size of the persistent disk of the application (in MB).
disk: 512

# Set a local R/W mount for logs
mounts:
    'logs':
        source: local
        source_path: logs
